#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Script to generate project folder structure
Tạo cấu trúc thư mục dự án thành file text
"""

import os
import sys
from pathlib import Path

def should_ignore(path, ignore_patterns):
    """Kiểm tra xem file/folder có nên bỏ qua không"""
    path_str = str(path)
    for pattern in ignore_patterns:
        if pattern in path_str:
            return True
    return False

def get_tree(directory, prefix="", ignore_patterns=None, max_depth=None, current_depth=0):
    """
    Tạo cấu trúc cây thư mục
    
    Args:
        directory: Đường dẫn thư mục cần duyệt
        prefix: Tiền tố hiển thị (dùng cho cây)
        ignore_patterns: Danh sách pattern cần bỏ qua
        max_depth: Độ sâu tối đa (None = không giới hạn)
        current_depth: Độ sâu hiện tại
    
    Returns:
        String chứa cấu trúc cây
    """
    if ignore_patterns is None:
        ignore_patterns = [
            'node_modules',
            '.git',
            '__pycache__',
            '.env',
            '.DS_Store',
            'Thumbs.db',
            '.vscode',
            '.idea',
            'dist',
            'build',
            '.next',
            '.cache',
            'z-demo',
            'z_demo',
            '.html',
            '.zip'
        ]
    
    # Kiểm tra độ sâu
    if max_depth is not None and current_depth >= max_depth:
        return ""
    
    tree_str = ""
    
    try:
        entries = sorted(os.listdir(directory))
    except PermissionError:
        return f"{prefix}[Permission Denied]\n"
    
    # Lọc entries
    entries = [e for e in entries if not should_ignore(
        os.path.join(directory, e), ignore_patterns
    )]
    
    for i, entry in enumerate(entries):
        path = os.path.join(directory, entry)
        is_last = i == len(entries) - 1
        current_prefix = "└── " if is_last else "├── "
        next_prefix = prefix + ("    " if is_last else "│   ")
        
        if os.path.isdir(path):
            tree_str += f"{prefix}{current_prefix}{entry}/\n"
            tree_str += get_tree(path, next_prefix, ignore_patterns, max_depth, current_depth + 1)
        else:
            tree_str += f"{prefix}{current_prefix}{entry}\n"
    
    return tree_str

def count_files_and_folders(directory, ignore_patterns=None):
    """Đếm số file và folder"""
    if ignore_patterns is None:
        ignore_patterns = [
            'node_modules',
            '.git',
            '__pycache__',
            '.env',
            '.DS_Store',
            'Thumbs.db',
            '.vscode',
            '.idea',
            'dist',
            'build',
            '.next',
            '.cache',
            'z-demo',
            'z_demo',
            '.html',
            '.zip'
        ]
    
    files = 0
    folders = 0
    
    for root, dirs, file_list in os.walk(directory):
        # Lọc directories
        dirs[:] = [d for d in dirs if not should_ignore(
            os.path.join(root, d), ignore_patterns
        )]
        
        # Lọc files
        for file in file_list:
            if not should_ignore(os.path.join(root, file), ignore_patterns):
                files += 1
        
        folders += len(dirs)
    
    return files, folders

def generate_structure(project_path, output_file=None, max_depth=None):
    """
    Tạo file cấu trúc dự án
    
    Args:
        project_path: Đường dẫn dự án
        output_file: File output (None = in ra console)
        max_depth: Độ sâu tối đa
    """
    
    if not os.path.exists(project_path):
        print(f"❌ Error: Đường dẫn '{project_path}' không tồn tại!")
        return False
    
    if not os.path.isdir(project_path):
        print(f"❌ Error: '{project_path}' không phải thư mục!")
        return False
    
    project_name = os.path.basename(project_path) or project_path
    
    print(f"📁 Đang tạo cấu trúc cho: {project_name}")
    print(f"📍 Đường dẫn: {project_path}")
    
    # Đếm file và folder
    file_count, folder_count = count_files_and_folders(project_path)
    
    # Tạo chuỗi cấu trúc
    structure = f"{project_name}/\n"
    structure += get_tree(project_path, "", max_depth=max_depth)
    
    # Tạo nội dung đầy đủ
    content = f"""# PROJECT STRUCTURE
# Cấu trúc thư mục dự án
# Generated by generate_structure.py

Project: {project_name}
Path: {project_path}
Date: {os.popen('date').read().strip() if sys.platform != 'win32' else 'N/A'}

Statistics / Thống kê:
- Folders / Thư mục: {folder_count}
- Files / File: {file_count}

Ignored Patterns / Các pattern bị bỏ qua:
- node_modules/
- .git/
- __pycache__/
- .env
- .DS_Store
- Thumbs.db
- .vscode/
- .idea/
- dist/
- build/
- .next/
- .cache/
- z-demo/
- z_demo/
- *.html (demo files)
- *.zip

═══════════════════════════════════════════════════════════════

STRUCTURE / CẤU TRÚC:

{structure}

═══════════════════════════════════════════════════════════════
"""
    
    # Output
    if output_file:
        output_path = os.path.join(project_path, output_file)
        try:
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write(content)
            print(f"✅ File tạo thành công: {output_path}")
            return True
        except Exception as e:
            print(f"❌ Error khi tạo file: {e}")
            return False
    else:
        print(content)
        return True

def main():
    """Hàm chính"""
    print("""
╔═══════════════════════════════════════════════════════════════╗
║         PROJECT STRUCTURE GENERATOR / TẠO CẤU TRÚC DỰ ÁN      ║
╚═══════════════════════════════════════════════════════════════╝
    """)
    
    # Lấy input từ user
    if len(sys.argv) > 1:
        project_path = sys.argv[1]
    else:
        project_path = input("📂 Nhập đường dẫn dự án: ").strip()
        if not project_path:
            project_path = "."
    
    # Normalize path
    project_path = os.path.abspath(project_path)
    
    # Chọn output
    print("\n📝 Lựa chọn cách lưu:")
    print("1. Lưu vào file STRUCTURE.txt")
    print("2. In ra console (terminal)")
    
    choice = input("Chọn (1 hoặc 2): ").strip()
    
    output_file = None
    if choice == "1":
        output_file = "STRUCTURE.txt"
    
    # Chọn độ sâu
    print("\n🔍 Độ sâu tìm kiếm:")
    print("1. Không giới hạn (tất cả)")
    print("2. 2 cấp")
    print("3. 3 cấp")
    print("4. 4 cấp")
    print("5. 5 cấp")
    
    depth_choice = input("Chọn (1-5): ").strip()
    max_depth = None
    if depth_choice in ["2", "3", "4", "5"]:
        max_depth = int(depth_choice)
    
    # Tạo cấu trúc
    success = generate_structure(project_path, output_file, max_depth)
    
    if success:
        print("\n✨ Thành công!")
        if output_file:
            print(f"💾 File được lưu tại: {os.path.join(project_path, output_file)}")
    else:
        print("\n❌ Có lỗi xảy ra!")
        sys.exit(1)

if __name__ == "__main__":
    main()