const mongoose = require('mongoose');
require('dotenv').config();
const Story = require('./models/Story');
const Chapter = require('./models/Chapter');
const User = require('./models/User');

const seedDatabase = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('MongoDB connected');

    // Find or create admin user
    let adminUser = await User.findOne({ email: 'tmy300803@gmail.com' });
    if (!adminUser) {
      adminUser = await User.create({
        username: 'tmy300803',
        email: 'tmy300803@gmail.com',
        password: 'hashedPassword123',
        role: 'admin'
      });
    }

    // Clear existing data
    await Story.deleteMany({});
    await Chapter.deleteMany({});
    console.log('Cleared existing data');

    // Create stories (slug will be generated by pre-save hook)
    const storyData = [
      {
        title: 'Yêu Em Từ Cái Nhìn Đầu Tiên',
        author: 'Nguyệt Hạ',
        authorId: adminUser._id,
        description: 'Một câu chuyện tình yêu ngọt ngào giữa hai người trẻ.',
        coverImage: 'https://via.placeholder.com/300x400?text=Story1',
        category: 'Ngôn tình',
        status: 'Đang ra',
        views: 1500,
        featured: true
      },
      {
        title: 'Thanh Gươm Diệt Quỷ',
        author: 'Tích Tích',
        authorId: adminUser._id,
        description: 'Hành trình của một kiếm sĩ trẻ chống lại những quyền lực bóng tối.',
        coverImage: 'https://via.placeholder.com/300x400?text=Story2',
        category: 'Kiếm hiệp',
        status: 'Đang ra',
        views: 2300,
        featured: true
      },
      {
        title: 'Hồng Trần Luyến',
        author: 'Mác Thúy',
        authorId: adminUser._id,
        description: 'Câu chuyện về một nữ hiệp bí ẩn và những âm mưu triều đình.',
        coverImage: 'https://via.placeholder.com/300x400?text=Story3',
        category: 'Tiên hiệp',
        status: 'Đang ra',
        views: 3200,
        featured: false
      },
      {
        title: 'Võ Ảnh Kiêm',
        author: 'Phong Nguyệt',
        authorId: adminUser._id,
        description: 'Một võ sư trẻ bắt đầu cuộc hành trình tìm kiếm sức mạnh.',
        coverImage: 'https://via.placeholder.com/300x400?text=Story4',
        category: 'Huyền huyễn',
        status: 'Hoàn thành',
        views: 5600,
        featured: false
      },
      {
        title: 'Độc Bộ Thiên Hạ',
        author: 'Giang Lạc',
        authorId: adminUser._id,
        description: 'Câu chuyện về sự trỗi dậy của một đại hiệp.',
        coverImage: 'https://via.placeholder.com/300x400?text=Story5',
        category: 'Đô thị',
        status: 'Đang ra',
        views: 1200,
        featured: false
      },
      {
        title: 'Lam Điệp Cô Ảnh',
        author: 'Lam Điệp Cô Ảnh',
        authorId: adminUser._id,
        description: 'Một câu chuyện về tình yêu và số phận giữa một nữ hiệp bí ẩn và một vị hoàng tử bị lưu đày.',
        coverImage: 'https://via.placeholder.com/300x400?text=LamDiep',
        category: 'Tiên hiệp',
        status: 'Đang ra',
        views: 8900,
        featured: true
      },
      {
        title: 'Ngạo Thế Cửu Trùng Thiên',
        author: 'Phong Lăng Thiên Hạ',
        authorId: adminUser._id,
        description: 'Tu tiên giả từ thấp đến cao, vượt qua chín tầng trời.',
        coverImage: 'https://via.placeholder.com/300x400?text=Story6',
        category: 'Tiên hiệp',
        status: 'Đang ra',
        views: 3100,
        featured: false
      },
      {
        title: 'Linh Vũ Thiên Hạ',
        author: 'Đông Tà',
        authorId: adminUser._id,
        description: 'Trong thời đại linh khí phục hồi, thiếu niên có thể triệu hồi linh thú chiến đấu.',
        coverImage: 'https://via.placeholder.com/300x400?text=Story7',
        category: 'Huyền huyễn',
        status: 'Đang ra',
        views: 2800,
        featured: false
      },
      {
        title: 'Phàm Nhân Tu Tiên',
        author: 'Vong Ngữ',
        authorId: adminUser._id,
        description: 'Từ một phàm nhân bình thường, bước lên con đường tu tiên gian khổ.',
        coverImage: 'https://via.placeholder.com/300x400?text=Story8',
        category: 'Tiên hiệp',
        status: 'Đang ra',
        views: 4200,
        featured: false
      }
    ];

    // Create stories with save() to trigger pre-save hook
    const stories = [];
    for (const data of storyData) {
      const story = new Story(data);
      await story.save();
      stories.push(story);
      console.log(`Created story with slug: ${story.slug}`);
    }

    console.log(`\nCreated ${stories.length} stories`);

    // Create chapters for each story
    let totalChapters = 0;
    for (const story of stories) {
      const chapters = [];
      for (let i = 1; i <= 5; i++) {
        chapters.push({
          storyId: story._id,
          chapterNumber: i,
          title: `Chương ${i}: ${story.title}`,
          content: `Đây là nội dung của chương ${i} của truyện "${story.title}". Nội dung truyện sẽ được cập nhật sau.`,
          views: Math.floor(Math.random() * 1000)
        });
      }
      await Chapter.insertMany(chapters);
      story.chapterCount = 5;
      await story.save();
      totalChapters += chapters.length;
    }

    console.log(`Created ${totalChapters} chapters`);
    console.log('Database seeded successfully!');
    process.exit(0);
  } catch (error) {
    console.error('Error seeding database:', error);
    process.exit(1);
  }
};

seedDatabase();
